db:
  name: pgdb01
  group: pgdb01
  instances: 2
  size: 8000Gi
  superUser:
    usernameKey: username
    passwordKey: password
    secretPath: gdex/pgdb01
  resource:
    limits:
      cpu: '16'
      memory: 128Gi
  
  backups:
    s3:
      enabled: false
