db:
  name: pgdb02
  group: pgdb02
  instances: 2
  size: 5001Gi
  superUser:
    usernameKey: username
    passwordKey: password
    replicationUserKey: repuser
    replicationPassKey: reppass
    secretPath: gdex/pgdb02
  resource:
    limits:
      cpu: '16'
      memory: 128Gi
  backups:
    volumeSnapshot:
      enabled: true
      snapshotClassName: csi-rbdplugin-snapclass
    s3:
      enabled: false
      secretName: backup-rgw-creds
      endpointURL: https://s3.k8s.ucar.edu:5443
      destinationPath: s3://pgdb02/
      secretPath: gdex/boreas
